=== pypi-data/pypi-mirror-8/packages/distlib/distlib-0.2.0.zip/distlib-0.2.0/tests/pydist-schema.json
{
  "id": "http://www.python.org/dev/peps/pep-0426/",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Metadata for Python Software Packages 2.0",
  "type": "object",
  "properties": {
    "metadata_version": {
      "description": "Version of the file format",
      "type": "string",
      "pattern": "^(\\d+(\\.\\d+)*)$"
    },
    "generator": {
      "description": "Name and version of the program that produced this file.",
      "type": "string",
      "pattern": "^[0-9A-Za-z]([0-9A-Za-z_.-]*[0-9A-Za-z])( \\(.*\\))?$"
    },
    "name": {
      "description": "The name of the distribution.",
      "type": "string",
      "$ref": "#/definitions/valid_name"
    },
    "version": {
      "description": "The distribution's public version identifier",
      "type": "string",
      "pattern": "^(\\d+(\\.\\d+)*)((a|b|c|rc)(\\d+))?(\\.(post)(\\d+))?(\\.(dev)(\\d+))?$"
    },
    "source_label": {
      "description": "A constrained identifying text string",
      "type": "string",
      "pattern": "^[0-9a-z_.-+]+$"
    },
    "source_url": {
      "description": "A string containing a full URL where the source for this specific version of the distribution can be downloaded.",
      "type": "string",
      "format": "uri"
    },
    "summary": {
      "description": "A one-line summary of what the distribution does.",
      "type": "string"
    },
    "document_names": {
      "description": "Names of supporting metadata documents",
      "type": "object",
      "properties": {
        "description": {
          "type": "string",
          "$ref": "#/definitions/document_name"
        },
        "changelog": {
          "type": "string",
          "$ref": "#/definitions/document_name"
        },
        "license": {
          "type": "string",
          "$ref": "#/definitions/document_name"
        }
      },
      "additionalProperties": false
    },
    "keywords": {
      "description": "A list of additional keywords to be used to assist searching for the distribution in a larger catalog.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "license": {
      "description": "A string indicating the license covering the distribution.",
      "type": "string"
    },
    "classifiers": {
      "description": "A list of strings, with each giving a single classification value for the distribution.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "contacts": {
      "description": "A list of contributor entries giving the recommended contact points for getting more information about the project.",
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "#/definitions/contact"
      }
    },
    "contributors": {
      "description": "A list of contributor entries for other contributors not already listed as current project points of contact.",
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "#/definitions/contact"
      }
    },
    "project_urls": {
      "description": "A mapping of arbitrary text labels to additional URLs relevant to the project.",
      "type": "object"
    },
    "extras": {
      "description": "A list of optional sets of dependencies that may be used to define conditional dependencies in \"may_require\" and similar fields.",
      "type": "array",
      "items": {
        "type": "string",
        "$ref": "#/definitions/extra_name"
      }
    },
    "meta_requires": {
      "description": "A list of subdistributions made available through this metadistribution.",
      "type": "array",
      "$ref": "#/definitions/dependencies"
    },
    "run_requires": {
      "description": "A list of other distributions needed to run this distribution.",
      "type": "array",
      "$ref": "#/definitions/dependencies"
    },
    "test_requires": {
      "description": "A list of other distributions needed when this distribution is tested.",
      "type": "array",
      "$ref": "#/definitions/dependencies"
    },
    "build_requires": {
      "description": "A list of other distributions needed when this distribution is built.",
      "type": "array",
      "$ref": "#/definitions/dependencies"
    },
    "dev_requires": {
      "description": "A list of other distributions needed when this distribution is developed.",
      "type": "array",
      "$ref": "#/definitions/dependencies"
    },
    "provides": {
      "description": "A list of strings naming additional dependency requirements that are satisfied by installing this distribution. These strings must be of the form Name or Name (Version)",
      "type": "array",
      "items": {
        "type": "string",
        "$ref": "#/definitions/provides_declaration"
      }
    },
    "obsoleted_by": {
      "description": "A string that indicates that this project is no longer being developed. The named project provides a substitute or replacement.",
      "type": "string",
      "$ref": "#/definitions/requirement"
    },
    "supports_environments": {
      "description": "A list of strings specifying the environments that the distribution explicitly supports.",
      "type": "array",
      "items": {
        "type": "string",
        "$ref": "#/definitions/environment_marker"
      }
    },
    "install_hooks": {
      "description": "The install_hooks field is used to define various operations that may be invoked on a distribution in a platform independent manner.",
      "type": "object",
      "properties": {
        "postinstall": {
          "type": "string",
          "$ref": "#/definitions/entry_point"
        },
        "preuninstall": {
          "type": "string",
          "$ref": "#/definitions/entry_point"
        }
      }
    },
    "extensions": {
      "description": "Extensions to the metadata may be present in a mapping under the 'extensions' key.",
      "type": "object"
    }
  },

  "required": ["metadata_version", "name", "version", "summary"],
  "additionalProperties": false,

  "definitions": {
    "contact": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "role": {
          "type": "string"
        }
      },
      "required": ["name"],
      "additionalProperties": false
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "#/definitions/dependency"
      }
    },
    "dependency": {
      "type": "object",
      "properties": {
        "extra": {
          "type": "string",
          "$ref": "#/definitions/valid_name"
        },
        "environment": {
          "type": "string",
          "$ref": "#/definitions/environment_marker"
        },
        "requires": {
          "type": "array",
          "items": {
            "type": "string",
            "$ref": "#/definitions/requirement"
          }
        }
      },
      "required": ["requires"],
      "additionalProperties": false
    },
    "valid_name": {
        "type": "string",
        "pattern": "^[0-9A-Za-z]([0-9A-Za-z_.-]*[0-9A-Za-z])?$"
    },
    "requirement": {
        "type": "string"
    },
    "provides_declaration": {
        "type": "string"
    },
    "environment_marker": {
        "type": "string"
    },
    "entry_point": {
        "type": "string"
    },
    "document_name": {
        "type": "string"
    },
    "extra_name" : {
        "type": "string"
    }
  }
}

=== pypi-data/pypi-mirror-8/packages/django-sayit/django_sayit-1.3-py2-none-any.whl/django_sayit-1.3.dist-info/metadata.json
{"name": "django-sayit", "metadata_version": "2.0", "generator": "bdist_wheel (0.24.0)", "summary": "A data store for speeches and transcripts to make them searchable and pretty.", "run_requires": [{"requires": ["beautifulsoup4", "requests-cache"], "extra": "scraping"}, {"requires": ["psycopg2 (>=2.5.1,<2.6)", "pytz (>=2013d)", "six (>=1.4.1)", "Django (>=1.4.2,<1.8)", "Django-Select2 (>=4.2.2,<4.3)", "django-qmethod (==0.0.3)", "audioread (>=1.0.1)", "pyelasticsearch (>=0.6,<0.7)", "django-haystack (>=2.1,<2.2)", "django-bleach (>=0.2.1)", "mysociety-django-popolo (>=0.0.2)", "mysociety-django-sluggable (>=0.2.6)", "django-subdomain-instances (>=0.10.2)", "easy-thumbnails (>=2.1)", "unicode-slugify (==0.1.1)", "pyOpenSSL (==0.14)", "ndg-httpsclient (==0.3.2)", "pyasn1 (==0.1.7)"]}, {"requires": ["selenium", "mock", "django-nose (==1.2)", "Mutagen", "lxml", "python-dateutil (<2)"], "extra": "test"}, {"requires": ["flake8", "django-debug-toolbar", "South (==1.0)", "popit-django (==0.0.3)"], "extra": "develop"}], "version": "1.3", "extensions": {"python.details": {"project_urls": {"Home": "https://github.com/mysociety/sayit"}, "document_names": {"description": "DESCRIPTION.rst"}, "contacts": [{"role": "author", "email": "sayit@mysociety.org", "name": "mySociety"}]}}, "classifiers": ["Development Status :: 5 - Production/Stable", "Environment :: Web Environment", "Framework :: Django", "License :: OSI Approved :: GNU Affero General Public License v3", "Intended Audience :: Developers", "Programming Language :: Python", "Programming Language :: Python :: 2", "Programming Language :: Python :: 3", "Topic :: Database :: Front-Ends", "Topic :: Internet :: WWW/HTTP"], "extras": ["develop", "scraping", "test"]}

=== pypi-data/pypi-mirror-8/packages/splash/splash-1.2-py2-none-any.whl/splash-1.2.dist-info/metadata.json
{"license": "BSD", "name": "splash", "metadata_version": "2.0", "generator": "bdist_wheel (0.24.0)", "summary": "A javascript rendered with a HTTP API", "run_requires": [{"requires": ["Twisted", "qt4reactor", "psutil", "adblockparser", "xvfbwrapper"]}], "version": "1.2", "extensions": {"python.details": {"project_urls": {"Home": "https://github.com/scrapinghub/splash"}, "document_names": {"description": "DESCRIPTION.rst"}, "contacts": [{"role": "author", "email": "info@scrapinghub.com", "name": "Scrapinghub"}]}}, "classifiers": ["Programming Language :: Python", "Programming Language :: Python :: 2", "Programming Language :: Python :: 2.7", "License :: OSI Approved :: BSD License", "Operating System :: OS Independent", "Development Status :: 5 - Production/Stable", "Environment :: Console", "Environment :: No Input/Output (Daemon)", "Topic :: Internet :: WWW/HTTP"], "extras": []}

=== pypi-data/pypi-mirror-8/packages/sloth-ci/sloth_ci-1.1.7-py3-none-any.whl/sloth_ci-1.1.7.dist-info/metadata.json
{"version": "1.1.7", "summary": "Simple app for automatization of everything", "metadata_version": "2.0", "run_requires": [{"requires": ["sloth-ci.ext.logs"], "extra": "Logs"}, {"requires": ["CherryPy", "awesome-slugify", "docopt", "tabulate", "PyYAML", "requests", "Routes"]}], "extensions": {"python.commands": {"wrap_console": {"sloth-ci": "sloth_ci.cli:main"}}, "python.details": {"contacts": [{"email": "moigagoo@live.com", "name": "Konstantin Molchanov", "role": "author"}], "document_names": {"description": "DESCRIPTION.rst"}, "project_urls": {"Home": "https://bitbucket.org/moigagoo/sloth-ci"}}, "python.exports": {"console_scripts": {"sloth-ci": "sloth_ci.cli:main"}}}, "name": "sloth-ci", "generator": "bdist_wheel (0.24.0)", "classifiers": ["Development Status :: 5 - Production/Stable", "Intended Audience :: Developers", "Natural Language :: English", "Programming Language :: Python", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.3", "Programming Language :: Python :: 3.4", "Programming Language :: Python :: 3 :: Only", "Operating System :: Microsoft :: Windows", "Operating System :: Unix", "Framework :: CherryPy"], "license": "MIT", "extras": ["Logs"]}

=== pypi-data/pypi-mirror-8/packages/django-content-toolkit/django_content_toolkit-0.1.3-py3-none-any.whl/django_content_toolkit-0.1.3.dist-info/metadata.json
{"generator": "bdist_wheel (0.24.0)", "summary": "A simple Django package for model translations", "extensions": {"python.details": {"project_urls": {"Home": "https://github.com/esistgut/django-content-toolkit"}, "document_names": {"description": "DESCRIPTION.rst"}, "contacts": [{"email": "g.graziosi@gmail.com", "role": "author", "name": "Giacomo Graziosi"}]}}, "name": "django-content-toolkit", "license": "MIT", "version": "0.1.3", "run_requires": [{"requires": ["Django", "django-polymorphic", "django-reversion", "django-mptt", "django-taggit"]}], "extras": [], "metadata_version": "2.0", "classifiers": ["Environment :: Web Environment", "Framework :: Django", "Intended Audience :: Developers", "Operating System :: OS Independent", "Programming Language :: Python", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.4", "Topic :: Internet :: WWW/HTTP", "Topic :: Internet :: WWW/HTTP :: Dynamic Content"]}

=== pypi-data/pypi-mirror-8/packages/frigg-coverage/frigg_coverage-0.4.0-py2.py3-none-any.whl/frigg_coverage-0.4.0.dist-info/metadata.json
{"generator": "bdist_wheel (0.24.0)", "classifiers": ["Programming Language :: Python", "Programming Language :: Python :: 3"], "metadata_version": "2.0", "summary": "Coverage report reading util", "extensions": {"python.details": {"project_urls": {"Home": "https://github.com/frigg/frigg-coverage"}, "contacts": [{"role": "author", "name": "The frigg team", "email": "hi@frigg.io"}], "document_names": {"description": "DESCRIPTION.rst"}}}, "name": "frigg-coverage", "version": "0.4.0", "extras": [], "run_requires": [{"requires": ["lxml"]}], "license": "MIT"}

=== pypi-data/pypi-mirror-8/packages/cloudwatch-to-graphite/cloudwatch_to_graphite-0.3.0-py2.py3-none-any.whl/cloudwatch_to_graphite-0.3.0.dist-info/metadata.json
{"license": "Apache License, Version 2.0", "name": "cloudwatch-to-graphite", "metadata_version": "2.0", "generator": "bdist_wheel (0.24.0)", "summary": "Helper for pushing AWS CloudWatch metrics to Graphite", "run_requires": [{"requires": ["boto", "PyYAML", "docopt", "Jinja2"]}], "version": "0.3.0", "extensions": {"python.details": {"project_urls": {"Home": "https://github.com/crccheck/cloudwatch-to-graphite"}, "document_names": {"description": "DESCRIPTION.rst"}, "contacts": [{"role": "author", "email": "c@crccheck.com", "name": "Chris Chang"}]}, "python.commands": {"wrap_console": {"leadbutt": "leadbutt:main", "plumbum": "plumbum:main"}}, "python.exports": {"console_scripts": {"leadbutt": "leadbutt:main", "plumbum": "plumbum:main"}}}, "classifiers": ["Development Status :: 3 - Alpha", "Environment :: Web Environment", "Intended Audience :: Developers", "License :: OSI Approved :: Apache Software License", "Operating System :: OS Independent", "Programming Language :: Python :: 2", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.4"], "extras": []}

=== pypi-data/pypi-mirror-8/packages/rubygemsrecipe/rubygemsrecipe-0.2.1-py3-none-any.whl/rubygemsrecipe-0.2.1.dist-info/metadata.json
{"version": "0.2.1", "metadata_version": "2.0", "test_requires": [{"requires": ["mock", "pathlib"]}], "extras": [], "classifiers": ["Framework :: Buildout", "Intended Audience :: Developers", "License :: OSI Approved :: GNU General Public License (GPL)", "Topic :: Software Development :: Libraries :: Ruby Modules", "Programming Language :: Python :: 2", "Programming Language :: Python :: 3"], "summary": "zc.buildout recipe for installing ruby gems.", "license": "GPL", "generator": "bdist_wheel (0.24.0)", "name": "rubygemsrecipe", "run_requires": [{"requires": ["six", "zc.buildout", "setuptools", "hexagonit.recipe.download"]}], "extensions": {"python.details": {"project_urls": {"Home": "https://bitbucket.org/sirex/rubygemsrecipe"}, "contacts": [{"name": "Mantas Zimnickas", "email": "sirexas@gmail.com", "role": "author"}], "document_names": {"description": "DESCRIPTION.rst"}}, "python.exports": {"zc.buildout": {"default": "rubygems:Recipe"}}}}

=== pypi-data/pypi-mirror-8/packages/lda/lda-0.3.2-cp34-none-win_amd64.whl/lda-0.3.2.dist-info/metadata.json
{"test_requires": [{"requires": ["scipy (>=0.10.1)", "hacking (>=0.9.2,<0.10)", "coverage (>=3.6)", "discover", "python-subunit", "sphinx (>=1.1.2)", "oslosphinx", "oslotest (>=1.1.0.0a2)", "testrepository (>=0.0.18)", "testscenarios (>=0.4)", "testtools (>=0.9.34)", "numpydoc (>=0.5)", "sphinx-rtd-theme (>=0.1.6)", "flake8 (>=2.1.0)", "Cython (>=0.19)"]}], "generator": "bdist_wheel (0.24.0)", "extras": [], "run_requires": [{"requires": ["pbr (>=0.6,!=0.7,<1.0)", "numpy (>=1.6.1,<2.0)"]}], "metadata_version": "2.0", "version": "0.3.2", "name": "lda", "extensions": {"python.details": {"contacts": [{"name": "lda developers", "email": "lda-users@googlegroups.com", "role": "author"}], "document_names": {"description": "DESCRIPTION.rst"}}}, "summary": "Topic modeling with latent Dirichlet allocation", "classifiers": ["Development Status :: 4 - Beta", "Intended Audience :: Information Technology", "Intended Audience :: Developers", "Intended Audience :: Science/Research", "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)", "Programming Language :: C", "Programming Language :: Cython", "Programming Language :: Python", "Programming Language :: Python :: 2", "Programming Language :: Python :: 3", "Operating System :: MacOS", "Operating System :: Microsoft :: Windows", "Operating System :: POSIX", "Operating System :: Unix"]}
