=== pypi-data/pypi-mirror-8/packages/distlib/distlib-0.2.0.zip/distlib-0.2.0/tests/pydist-schema.json
{
  "id": "http://www.python.org/dev/peps/pep-0426/",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Metadata for Python Software Packages 2.0",
  "type": "object",
  "properties": {
    "metadata_version": {
      "description": "Version of the file format",
      "type": "string",
      "pattern": "^(\\d+(\\.\\d+)*)$"
    },
    "generator": {
      "description": "Name and version of the program that produced this file.",
      "type": "string",
      "pattern": "^[0-9A-Za-z]([0-9A-Za-z_.-]*[0-9A-Za-z])( \\(.*\\))?$"
    },
    "name": {
      "description": "The name of the distribution.",
      "type": "string",
      "$ref": "#/definitions/valid_name"
    },
    "version": {
      "description": "The distribution's public version identifier",
      "type": "string",
      "pattern": "^(\\d+(\\.\\d+)*)((a|b|c|rc)(\\d+))?(\\.(post)(\\d+))?(\\.(dev)(\\d+))?$"
    },
    "source_label": {
      "description": "A constrained identifying text string",
      "type": "string",
      "pattern": "^[0-9a-z_.-+]+$"
    },
    "source_url": {
      "description": "A string containing a full URL where the source for this specific version of the distribution can be downloaded.",
      "type": "string",
      "format": "uri"
    },
    "summary": {
      "description": "A one-line summary of what the distribution does.",
      "type": "string"
    },
    "document_names": {
      "description": "Names of supporting metadata documents",
      "type": "object",
      "properties": {
        "description": {
          "type": "string",
          "$ref": "#/definitions/document_name"
        },
        "changelog": {
          "type": "string",
          "$ref": "#/definitions/document_name"
        },
        "license": {
          "type": "string",
          "$ref": "#/definitions/document_name"
        }
      },
      "additionalProperties": false
    },
    "keywords": {
      "description": "A list of additional keywords to be used to assist searching for the distribution in a larger catalog.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "license": {
      "description": "A string indicating the license covering the distribution.",
      "type": "string"
    },
    "classifiers": {
      "description": "A list of strings, with each giving a single classification value for the distribution.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "contacts": {
      "description": "A list of contributor entries giving the recommended contact points for getting more information about the project.",
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "#/definitions/contact"
      }
    },
    "contributors": {
      "description": "A list of contributor entries for other contributors not already listed as current project points of contact.",
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "#/definitions/contact"
      }
    },
    "project_urls": {
      "description": "A mapping of arbitrary text labels to additional URLs relevant to the project.",
      "type": "object"
    },
    "extras": {
      "description": "A list of optional sets of dependencies that may be used to define conditional dependencies in \"may_require\" and similar fields.",
      "type": "array",
      "items": {
        "type": "string",
        "$ref": "#/definitions/extra_name"
      }
    },
    "meta_requires": {
      "description": "A list of subdistributions made available through this metadistribution.",
      "type": "array",
      "$ref": "#/definitions/dependencies"
    },
    "run_requires": {
      "description": "A list of other distributions needed to run this distribution.",
      "type": "array",
      "$ref": "#/definitions/dependencies"
    },
    "test_requires": {
      "description": "A list of other distributions needed when this distribution is tested.",
      "type": "array",
      "$ref": "#/definitions/dependencies"
    },
    "build_requires": {
      "description": "A list of other distributions needed when this distribution is built.",
      "type": "array",
      "$ref": "#/definitions/dependencies"
    },
    "dev_requires": {
      "description": "A list of other distributions needed when this distribution is developed.",
      "type": "array",
      "$ref": "#/definitions/dependencies"
    },
    "provides": {
      "description": "A list of strings naming additional dependency requirements that are satisfied by installing this distribution. These strings must be of the form Name or Name (Version)",
      "type": "array",
      "items": {
        "type": "string",
        "$ref": "#/definitions/provides_declaration"
      }
    },
    "obsoleted_by": {
      "description": "A string that indicates that this project is no longer being developed. The named project provides a substitute or replacement.",
      "type": "string",
      "$ref": "#/definitions/requirement"
    },
    "supports_environments": {
      "description": "A list of strings specifying the environments that the distribution explicitly supports.",
      "type": "array",
      "items": {
        "type": "string",
        "$ref": "#/definitions/environment_marker"
      }
    },
    "install_hooks": {
      "description": "The install_hooks field is used to define various operations that may be invoked on a distribution in a platform independent manner.",
      "type": "object",
      "properties": {
        "postinstall": {
          "type": "string",
          "$ref": "#/definitions/entry_point"
        },
        "preuninstall": {
          "type": "string",
          "$ref": "#/definitions/entry_point"
        }
      }
    },
    "extensions": {
      "description": "Extensions to the metadata may be present in a mapping under the 'extensions' key.",
      "type": "object"
    }
  },

  "required": ["metadata_version", "name", "version", "summary"],
  "additionalProperties": false,

  "definitions": {
    "contact": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "role": {
          "type": "string"
        }
      },
      "required": ["name"],
      "additionalProperties": false
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "#/definitions/dependency"
      }
    },
    "dependency": {
      "type": "object",
      "properties": {
        "extra": {
          "type": "string",
          "$ref": "#/definitions/valid_name"
        },
        "environment": {
          "type": "string",
          "$ref": "#/definitions/environment_marker"
        },
        "requires": {
          "type": "array",
          "items": {
            "type": "string",
            "$ref": "#/definitions/requirement"
          }
        }
      },
      "required": ["requires"],
      "additionalProperties": false
    },
    "valid_name": {
        "type": "string",
        "pattern": "^[0-9A-Za-z]([0-9A-Za-z_.-]*[0-9A-Za-z])?$"
    },
    "requirement": {
        "type": "string"
    },
    "provides_declaration": {
        "type": "string"
    },
    "environment_marker": {
        "type": "string"
    },
    "entry_point": {
        "type": "string"
    },
    "document_name": {
        "type": "string"
    },
    "extra_name" : {
        "type": "string"
    }
  }
}

=== pypi-data/pypi-mirror-8/packages/SoftLayer/SoftLayer-3.3.1-py2.py3-none-any.whl/SoftLayer-3.3.1.dist-info/metadata.json
{"license": "MIT", "name": "SoftLayer", "metadata_version": "2.0", "generator": "bdist_wheel (0.24.0)", "summary": "A library for SoftLayer's API", "run_requires": [{"requires": ["six (>=1.7.0)", "prettytable (>=0.7.0)", "docopt (==0.6.1)", "requests"]}], "version": "3.3.1", "extensions": {"python.details": {"project_urls": {"Home": "http://github.com/softlayer/softlayer-python"}, "document_names": {"description": "DESCRIPTION.rst"}, "contacts": [{"role": "author", "email": "sldn@softlayer.com", "name": "SoftLayer Technologies, Inc."}]}, "python.commands": {"wrap_console": {"sl": "SoftLayer.CLI.core:main"}}, "python.exports": {"console_scripts": {"sl": "SoftLayer.CLI.core:main"}}}, "classifiers": ["Environment :: Console", "Environment :: Web Environment", "Intended Audience :: Developers", "Intended Audience :: System Administrators", "License :: OSI Approved :: MIT License", "Operating System :: OS Independent", "Topic :: Software Development :: Libraries :: Python Modules", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.3", "Programming Language :: Python :: 3.2", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 2.6", "Programming Language :: Python :: Implementation :: CPython", "Programming Language :: Python :: Implementation :: PyPy"], "extras": []}

=== pypi-data/pypi-mirror-8/packages/httptestserver/httptestserver-0.1.1-py3-none-any.whl/httptestserver-0.1.1.dist-info/metadata.json
{"metadata_version": "2.0", "extensions": {"python.details": {"document_names": {"description": "DESCRIPTION.rst"}, "contacts": [{"name": "Javier Santacruz", "email": "javier.santacruz.lc@gmail.com", "role": "author"}]}}, "classifiers": ["Topic :: Software Development :: Testing"], "summary": "HTTP and HTTPS testing server", "name": "httptestserver", "generator": "bdist_wheel (0.24.0)", "version": "0.1.1"}

=== pypi-data/pypi-mirror-8/packages/django-user-management/django_user_management-3.0.0-py2.py3-none-any.whl/django_user_management-3.0.0.dist-info/metadata.json
{"extensions": {"python.details": {"contacts": [{"email": "admin@incuna.com", "name": "Incuna", "role": "author"}], "project_urls": {"Home": "https://github.com/incuna/django-user-management/"}, "document_names": {"description": "DESCRIPTION.rst"}}}, "summary": "User management model mixins and api views.", "metadata_version": "2.0", "generator": "bdist_wheel (0.24.0)", "run_requires": [{"extra": "avatar", "requires": ["django-imagekit (>=3.2)"]}, {"requires": ["djangorestframework (>=2.4.3,<3)", "incuna-mail (>=2.0.0,<3)"]}], "name": "django-user-management", "version": "3.0.0", "extras": ["avatar"]}

=== pypi-data/pypi-mirror-8/packages/pcf_decrypt/pcf_decrypt-0.1.1-py2.py3-none-any.whl/pcf_decrypt-0.1.1.dist-info/metadata.json
{"license": "MIT", "name": "pcf-decrypt", "metadata_version": "2.0", "generator": "bdist_wheel (0.24.0)", "test_requires": [{"requires": []}], "summary": "Decrypt encoded passwords in Cisco VPN pcf files.", "run_requires": [{"requires": ["six (>=1.8.0,<2.0.0)", "PyCrypto (>=2.6.1,<2.7.0)"]}], "version": "0.1.1", "extensions": {"python.details": {"project_urls": {"Home": "https://github.com/demosdemon/pcf_decrypt"}, "document_names": {"description": "DESCRIPTION.rst"}, "contacts": [{"role": "author", "email": "demosdemon@gmail.com", "name": "Joachim Brandon LeBlanc"}]}, "python.commands": {"wrap_console": {"pcf_decrypt": "pcf_decrypt.__main__:main"}}, "python.exports": {"console_scripts": {"pcf_decrypt": "pcf_decrypt.__main__:main"}}}, "keywords": ["pcf_decrypt"], "classifiers": ["Development Status :: 4 - Beta", "Intended Audience :: Developers", "Intended Audience :: System Administrators", "License :: OSI Approved :: MIT License", "Natural Language :: English", "Programming Language :: Python :: 2", "Programming Language :: Python :: 2.6", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.3", "Programming Language :: Python :: 3.4"], "extras": []}

=== pypi-data/pypi-mirror-8/packages/django-service-rating-store/django_service_rating_store-0.3.0-py2-none-any.whl/django_service_rating_store-0.3.0.dist-info/metadata.json
{"license": "BSD", "name": "django-service-rating-store", "metadata_version": "2.0", "generator": "bdist_wheel (0.24.0)", "summary": "Django app that allows storage and visualisation of Service Rating data posted via REST API", "run_requires": [{"requires": ["Django", "django-tastypie", "South"]}], "version": "0.3.0", "extensions": {"python.details": {"project_urls": {"Home": "https://github.com/praekelt/django-service-rating-store"}, "document_names": {"description": "DESCRIPTION.rst"}, "contacts": [{"role": "author", "email": "devops@praekeltfoundation.org", "name": "Praekelt Foundation"}]}}, "classifiers": ["Development Status :: 4 - Beta", "Intended Audience :: Developers", "License :: OSI Approved :: BSD License", "Operating System :: POSIX", "Programming Language :: Python", "Topic :: Software Development :: Libraries :: Python Modules", "Topic :: System :: Networking"], "extras": []}

=== pypi-data/pypi-mirror-8/packages/bvg-grabber/bvg_grabber-0.1.0-py2.py3-none-any.whl/bvg_grabber-0.1.0.dist-info/metadata.json
{"license": "BSD", "extras": [], "name": "bvg-grabber", "classifiers": ["Development Status :: 4 - Beta", "Environment :: Console", "Intended Audience :: Developers", "License :: OSI Approved :: BSD License", "Operating System :: OS Independent", "Programming Language :: Python", "Programming Language :: Python :: 3"], "metadata_version": "2.0", "generator": "bdist_wheel (0.24.0)", "run_requires": [{"requires": ["beautifulsoup4 (>=4.2.1)", "python-dateutil (>=2.1)", "requests (>=1.2.3)", "six (>=1.3.0)"]}], "summary": "Querying the upcoming public transport departures in Berlin", "version": "0.1.0", "extensions": {"python.details": {"project_urls": {"Home": "https://github.com/Markush2010/bvg-grabber"}, "contacts": [{"name": "Christian Struck, Markus Holtermann", "role": "author"}], "document_names": {"description": "DESCRIPTION.rst"}}}}

=== pypi-data/pypi-mirror-8/packages/switchpayments/switchpayments-0.1.0.dev1-py2.py3-none-any.whl/switchpayments-0.1.0.dev1.dist-info/metadata.json
{"license": "MIT", "name": "switchpayments", "metadata_version": "2.0", "generator": "bdist_wheel (0.24.0)", "summary": "SwitchPayments", "version": "0.1.0.dev1", "extensions": {"python.details": {"project_urls": {"Home": "https://pypi.python.org/pypi/test_pypi"}, "document_names": {"description": "DESCRIPTION.rst"}, "contacts": [{"role": "author", "email": "info@switchpayments.com", "name": "The Switch. Team"}]}}, "keywords": ["payment", "payments"], "classifiers": ["Development Status :: 3 - Alpha", "Intended Audience :: Developers", "Topic :: Software Development :: Libraries", "License :: OSI Approved :: MIT License", "Programming Language :: Python :: 2", "Programming Language :: Python :: 2.6", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.2", "Programming Language :: Python :: 3.3", "Programming Language :: Python :: 3.4"]}

=== pypi-data/pypi-mirror-8/packages/tailon/tailon-0.3.0-py2.py3-none-any.whl/tailon-0.3.0.dist-info/metadata.json
{"keywords": ["log", "monitoring", "tail"], "classifiers": ["Development Status :: 4 - Beta", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.3", "Programming Language :: Python :: 3.4", "License :: OSI Approved :: BSD License", "Intended Audience :: Developers", "Operating System :: POSIX :: Linux"], "name": "tailon", "run_requires": [{"requires": ["tornado (>=4.0.2)", "sockjs-tornado (>=1.0.1)", "PyYAML (>=3.11)"]}], "extras": [], "license": "Revised BSD License", "generator": "bdist_wheel (0.24.0)", "extensions": {"python.details": {"project_urls": {"Home": "https://github.com/gvalkov/tailon"}, "document_names": {"description": "DESCRIPTION.rst"}, "contacts": [{"role": "author", "email": "georgi.t.valkov@gmail.com", "name": "Georgi Valkov"}]}, "python.exports": {"console_scripts": {"tailon": "tailon.main:main"}}, "python.commands": {"wrap_console": {"tailon": "tailon.main:main"}}}, "version": "0.3.0", "summary": "Webapp for looking at and searching through log files", "metadata_version": "2.0"}
