=== pypi-data/pypi-mirror-8/packages/distlib/distlib-0.2.0.zip/distlib-0.2.0/tests/pydist-schema.json
{
  "id": "http://www.python.org/dev/peps/pep-0426/",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Metadata for Python Software Packages 2.0",
  "type": "object",
  "properties": {
    "metadata_version": {
      "description": "Version of the file format",
      "type": "string",
      "pattern": "^(\\d+(\\.\\d+)*)$"
    },
    "generator": {
      "description": "Name and version of the program that produced this file.",
      "type": "string",
      "pattern": "^[0-9A-Za-z]([0-9A-Za-z_.-]*[0-9A-Za-z])( \\(.*\\))?$"
    },
    "name": {
      "description": "The name of the distribution.",
      "type": "string",
      "$ref": "#/definitions/valid_name"
    },
    "version": {
      "description": "The distribution's public version identifier",
      "type": "string",
      "pattern": "^(\\d+(\\.\\d+)*)((a|b|c|rc)(\\d+))?(\\.(post)(\\d+))?(\\.(dev)(\\d+))?$"
    },
    "source_label": {
      "description": "A constrained identifying text string",
      "type": "string",
      "pattern": "^[0-9a-z_.-+]+$"
    },
    "source_url": {
      "description": "A string containing a full URL where the source for this specific version of the distribution can be downloaded.",
      "type": "string",
      "format": "uri"
    },
    "summary": {
      "description": "A one-line summary of what the distribution does.",
      "type": "string"
    },
    "document_names": {
      "description": "Names of supporting metadata documents",
      "type": "object",
      "properties": {
        "description": {
          "type": "string",
          "$ref": "#/definitions/document_name"
        },
        "changelog": {
          "type": "string",
          "$ref": "#/definitions/document_name"
        },
        "license": {
          "type": "string",
          "$ref": "#/definitions/document_name"
        }
      },
      "additionalProperties": false
    },
    "keywords": {
      "description": "A list of additional keywords to be used to assist searching for the distribution in a larger catalog.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "license": {
      "description": "A string indicating the license covering the distribution.",
      "type": "string"
    },
    "classifiers": {
      "description": "A list of strings, with each giving a single classification value for the distribution.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "contacts": {
      "description": "A list of contributor entries giving the recommended contact points for getting more information about the project.",
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "#/definitions/contact"
      }
    },
    "contributors": {
      "description": "A list of contributor entries for other contributors not already listed as current project points of contact.",
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "#/definitions/contact"
      }
    },
    "project_urls": {
      "description": "A mapping of arbitrary text labels to additional URLs relevant to the project.",
      "type": "object"
    },
    "extras": {
      "description": "A list of optional sets of dependencies that may be used to define conditional dependencies in \"may_require\" and similar fields.",
      "type": "array",
      "items": {
        "type": "string",
        "$ref": "#/definitions/extra_name"
      }
    },
    "meta_requires": {
      "description": "A list of subdistributions made available through this metadistribution.",
      "type": "array",
      "$ref": "#/definitions/dependencies"
    },
    "run_requires": {
      "description": "A list of other distributions needed to run this distribution.",
      "type": "array",
      "$ref": "#/definitions/dependencies"
    },
    "test_requires": {
      "description": "A list of other distributions needed when this distribution is tested.",
      "type": "array",
      "$ref": "#/definitions/dependencies"
    },
    "build_requires": {
      "description": "A list of other distributions needed when this distribution is built.",
      "type": "array",
      "$ref": "#/definitions/dependencies"
    },
    "dev_requires": {
      "description": "A list of other distributions needed when this distribution is developed.",
      "type": "array",
      "$ref": "#/definitions/dependencies"
    },
    "provides": {
      "description": "A list of strings naming additional dependency requirements that are satisfied by installing this distribution. These strings must be of the form Name or Name (Version)",
      "type": "array",
      "items": {
        "type": "string",
        "$ref": "#/definitions/provides_declaration"
      }
    },
    "obsoleted_by": {
      "description": "A string that indicates that this project is no longer being developed. The named project provides a substitute or replacement.",
      "type": "string",
      "$ref": "#/definitions/requirement"
    },
    "supports_environments": {
      "description": "A list of strings specifying the environments that the distribution explicitly supports.",
      "type": "array",
      "items": {
        "type": "string",
        "$ref": "#/definitions/environment_marker"
      }
    },
    "install_hooks": {
      "description": "The install_hooks field is used to define various operations that may be invoked on a distribution in a platform independent manner.",
      "type": "object",
      "properties": {
        "postinstall": {
          "type": "string",
          "$ref": "#/definitions/entry_point"
        },
        "preuninstall": {
          "type": "string",
          "$ref": "#/definitions/entry_point"
        }
      }
    },
    "extensions": {
      "description": "Extensions to the metadata may be present in a mapping under the 'extensions' key.",
      "type": "object"
    }
  },

  "required": ["metadata_version", "name", "version", "summary"],
  "additionalProperties": false,

  "definitions": {
    "contact": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "url": {
          "type": "string"
        },
        "role": {
          "type": "string"
        }
      },
      "required": ["name"],
      "additionalProperties": false
    },
    "dependencies": {
      "type": "array",
      "items": {
        "type": "object",
        "$ref": "#/definitions/dependency"
      }
    },
    "dependency": {
      "type": "object",
      "properties": {
        "extra": {
          "type": "string",
          "$ref": "#/definitions/valid_name"
        },
        "environment": {
          "type": "string",
          "$ref": "#/definitions/environment_marker"
        },
        "requires": {
          "type": "array",
          "items": {
            "type": "string",
            "$ref": "#/definitions/requirement"
          }
        }
      },
      "required": ["requires"],
      "additionalProperties": false
    },
    "valid_name": {
        "type": "string",
        "pattern": "^[0-9A-Za-z]([0-9A-Za-z_.-]*[0-9A-Za-z])?$"
    },
    "requirement": {
        "type": "string"
    },
    "provides_declaration": {
        "type": "string"
    },
    "environment_marker": {
        "type": "string"
    },
    "entry_point": {
        "type": "string"
    },
    "document_name": {
        "type": "string"
    },
    "extra_name" : {
        "type": "string"
    }
  }
}

=== pypi-data/pypi-mirror-8/packages/poker/poker-0.18.0-py3-none-any.whl/poker-0.18.0.dist-info/metadata.json
{"name": "poker", "summary": "Poker Framework", "test_requires": [{"requires": ["pytest", "coverage", "coveralls"]}], "classifiers": ["Intended Audience :: Developers", "Programming Language :: Python", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.4"], "generator": "bdist_wheel (0.24.0)", "license": "MIT", "extensions": {"python.commands": {"wrap_console": {"poker": "poker.scripts:poker"}}, "python.exports": {"console_scripts": {"poker": "poker.scripts:poker"}}, "python.details": {"contacts": [{"name": "Kiss Gy\u00f6rgy", "email": "kissgyorgy@me.com", "role": "author"}], "project_urls": {"Home": "https://github.com/pokerregion/poker"}, "document_names": {"description": "DESCRIPTION.rst"}}}, "metadata_version": "2.0", "run_requires": [{"requires": ["pytz", "requests", "lxml", "python-dateutil", "parsedatetime", "cached-property", "click", "enum34-custom"]}], "version": "0.18.0", "keywords": ["poker"], "extras": []}

=== pypi-data/pypi-mirror-8/packages/rmoq/rmoq-0.2.1-py2.py3-none-any.whl/rmoq-0.2.1.dist-info/metadata.json
{"generator": "bdist_wheel (0.24.0)", "extensions": {"python.details": {"document_names": {"description": "DESCRIPTION.rst"}, "project_urls": {"Home": "http://github.com/relekang/rmoq"}, "contacts": [{"name": "Rolf Erik Lekang", "email": "me@rolflekang.com", "role": "author"}]}}, "summary": "A simple request-mocker that will download", "classifiers": ["Programming Language :: Python", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3.4"], "metadata_version": "2.0", "name": "rmoq", "license": "MIT", "version": "0.2.1"}

=== pypi-data/pypi-mirror-8/packages/model-mommy/model_mommy-1.2.2-py2-none-any.whl/model_mommy-1.2.2.dist-info/metadata.json
{"license": "Apache 2.0", "name": "model-mommy", "metadata_version": "2.0", "generator": "bdist_wheel (0.24.0)", "test_requires": [{"requires": ["django (<1.8)", "pil", "tox"]}], "summary": "Smart object creation facility for Django.", "run_requires": [{"requires": ["Django (<1.8)", "six (==1.7.3)"]}], "version": "1.2.2", "extensions": {"python.details": {"project_urls": {"Home": "http://github.com/vandersonmota/model_mommy"}, "document_names": {"description": "DESCRIPTION.rst"}, "contacts": [{"role": "author", "email": "vandersonmota@gmail.com", "name": "vandersonmota"}]}}, "keywords": ["django", "testing", "factory", "python"], "classifiers": ["Framework :: Django", "Intended Audience :: Developers", "License :: OSI Approved :: Apache Software License", "Operating System :: OS Independent", "Topic :: Software Development", "Programming Language :: Python :: 2", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.3"], "extras": []}

=== pypi-data/pypi-mirror-8/packages/monasca-persister/monasca_persister-0.1.4-py2.py3-none-any.whl/monasca_persister-0.1.4.dist-info/metadata.json
{"metadata_version": "2.0", "name": "monasca-persister", "test_requires": [{"requires": ["hacking (>=0.9.2,<0.10)", "pyflakes", "nose", "mock (>=1.0.1)"]}], "version": "0.1.4", "license": "Apache", "extras": [], "generator": "bdist_wheel (0.24.0)", "run_requires": [{"requires": ["babel", "iso8601", "eventlet", "kafka-python (>=0.9.1)", "oslo.config (>=1.3.0)", "influxdb (>=0.1.12)"]}], "extensions": {"python.commands": {"wrap_console": {"monasca-persister": "monasca_persister.servicerunner:main"}}, "python.exports": {"console_scripts": {"monasca-persister": "monasca_persister.servicerunner:main"}}, "python.details": {"contacts": [{"email": "deklan.dieterly@hp.com", "name": "Deklan Dieterly", "role": "author"}], "project_urls": {"Home": "https://github.com/stackforge/monasca-persister"}, "document_names": {"description": "DESCRIPTION.rst"}}}, "summary": "UNKNOWN", "keywords": ["openstack", "monitoring", "storage"], "classifiers": ["Development Status :: 5 - Production/Stable", "License :: OSI Approved :: Apache Software License", "Topic :: System :: Monitoring"]}

=== pypi-data/pypi-mirror-8/packages/pelican_publications/pelican_publications-0.2.0-py2.py3-none-any.whl/pelican_publications-0.2.0.dist-info/metadata.json
{"license": "MIT", "document_names": {"description": "DESCRIPTION.rst"}, "name": "pelican-publications", "metadata_version": "2.0", "contacts": [{"role": "author", "email": "adreeve@gmail.com", "name": "Adam Reeve"}], "generator": "bdist_wheel (0.23.0)", "summary": "A Pelican plugin that adds an RST directive for including a BibTeX publication list.", "project_urls": {"Home": "https://github.com/adamreeve/pelican_publications"}, "run_requires": [{"requires": ["bibtexparser"]}], "version": "0.2.0", "classifiers": ["Development Status :: 3 - Alpha", "Operating System :: OS Independent", "Programming Language :: Python", "Programming Language :: Python :: 2", "Programming Language :: Python :: 3", "Programming Language :: Python :: 2.6", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3.2", "Programming Language :: Python :: 3.3", "Programming Language :: Python :: 3.4", "License :: OSI Approved :: MIT License", "Natural Language :: English", "Intended Audience :: Developers", "Topic :: Internet :: WWW/HTTP", "Topic :: Software Development :: Libraries :: Python Modules", "Topic :: Text Processing"], "extras": []}

=== pypi-data/pypi-mirror-8/packages/knossos/knossos-0.1.0.dev3-py2.py3-none-any.whl/knossos-0.1.0.dev3.dist-info/metadata.json
{"keywords": ["fso", "freespace"], "generator": "bdist_wheel (0.24.0)", "summary": "A simple mod manager for FreeSpace 2 Open", "name": "knossos", "metadata_version": "2.0", "extensions": {"python.commands": {"wrap_gui": {"knossos": "knossos.launcher:main"}}, "python.details": {"project_urls": {"Home": "https://github.com/ngld/knossos"}, "document_names": {"description": "DESCRIPTION.rst"}, "contacts": [{"role": "author", "name": "ngld", "email": "ngld@tproxy.de"}]}, "python.exports": {"gui_scripts": {"knossos": "knossos.launcher:main"}}}, "classifiers": ["Development Status :: 3 - Alpha", "Intended Audience :: End Users/Desktop", "License :: OSI Approved :: Apache Software License", "Programming Language :: Python :: 2", "Programming Language :: Python :: 2.7", "Programming Language :: Python :: 3", "Programming Language :: Python :: 3.2", "Programming Language :: Python :: 3.3", "Programming Language :: Python :: 3.4"], "extras": ["pyqt4", "pyside"], "run_requires": [{"requires": ["six", "requests", "semantic-version"]}, {"extra": "pyqt4", "requires": ["PyQt4"]}, {"extra": "pyside", "requires": ["PySide"]}], "version": "0.1.0.dev3"}

=== pypi-data/pypi-mirror-8/packages/Beetle/Beetle-0.7.1-py3-none-any.whl/Beetle-0.7.1.dist-info/metadata.json
{"name": "Beetle", "license": "MIT", "run_requires": [{"requires": ["PyYAML", "awesome-slugify", "Jinja2"]}], "extensions": {"python.commands": {"wrap_console": {"beetle": "beetle.cli:main"}}, "python.exports": {"console_scripts": {"beetle": "beetle.cli:main"}}, "python.details": {"contacts": [{"name": "Esben Sonne", "email": "esbensonne+code@gmail.com", "role": "author"}], "document_names": {"description": "DESCRIPTION.rst"}, "project_urls": {"Home": "https://github.com/cknv/beetle"}}}, "extras": [], "generator": "bdist_wheel (0.24.0)", "version": "0.7.1", "summary": "Beetle is a simple static site generator", "metadata_version": "2.0", "classifiers": ["Development Status :: 3 - Alpha", "Environment :: Console", "Environment :: Web Environment", "Intended Audience :: Developers", "License :: OSI Approved :: MIT License", "Natural Language :: English", "Operating System :: OS Independent", "Programming Language :: Python :: 3", "Programming Language :: Python", "Topic :: Text Processing"]}

=== pypi-data/pypi-mirror-8/packages/sqlcop/sqlcop-0.9.3-py2.py3-none-any.whl/sqlcop-0.9.3.dist-info/metadata.json
{"license": "BSD", "name": "sqlcop", "metadata_version": "2.0", "generator": "bdist_wheel (0.24.0)", "summary": "A cli tool to check and guard against anti-patterns", "run_requires": [{"requires": ["sqlparse (==0.1.14)", "memoized (==0.2)"]}], "version": "0.9.3", "extensions": {"python.details": {"project_urls": {"Home": "https://github.2ndsiteinc.com/kevin/sqlcop"}, "document_names": {"description": "DESCRIPTION.rst"}, "contacts": [{"role": "author", "email": "kevin@freshbooks.com", "name": "Kevin Qiu"}]}, "python.commands": {"wrap_console": {"sqlcop": "sqlcop.cli:main"}}, "python.exports": {"console_scripts": {"sqlcop": "sqlcop.cli:main"}}}, "keywords": ["sqlcop"], "classifiers": ["Development Status :: 2 - Pre-Alpha", "Intended Audience :: Developers", "License :: OSI Approved :: BSD License", "Natural Language :: English", "Programming Language :: Python :: 2", "Programming Language :: Python :: 2.6", "Programming Language :: Python :: 2.7"], "extras": []}
